/* GitHub Pages compatibility: browser-only demo API. Production/Render still uses server.js. */
(()=>{const P=location.protocol==='file:'||/(^|\.)github\.io$/i.test(location.hostname);if(!P)return;
const ADMIN=/admin(?:\.html)?$/i.test(location.pathname),K='contactscope-pages-v1',N=[
['c_1001','Maya Chen','VP of Growth','Northstar Labs','northstarlabs.example','SaaS','San Francisco, US','51–200','maya.chen@northstarlabs.example','+1 415 555 0142',97,'Company leadership page','2026-09-28'],
['c_1002','Owen Brooks','Head of Sales','OrbitIQ','orbitiq.example','Analytics','Austin, US','11–50','owen.brooks@orbitiq.example','+1 512 555 0188',94,'Public company directory','2026-09-26'],
['c_1003','Amina Rahman','Chief Marketing Officer','ClarityWorks','clarityworks.example','MarTech','London, UK','201–500','amina.rahman@clarityworks.example','+44 20 7946 0321',96,'Conference speaker profile','2026-10-01'],
['c_1004','Lucas Martin','Co-Founder & CEO','VertexCloud','vertexcloud.example','Cloud Infrastructure','Berlin, DE','51–200','lucas@vertexcloud.example','+49 30 5557 0194',92,'Public press release','2026-09-22'],
['c_1005','Sofia Alvarez','Director of Partnerships','BrightPath AI','brightpath.example','Artificial Intelligence','Madrid, ES','11–50','sofia.alvarez@brightpath.example','+34 91 555 0147',95,'Company team page','2026-09-30'],
['c_1006','Noah Wilson','VP Engineering','SignalNest','signalnest.example','Developer Tools','Toronto, CA','51–200','noah.wilson@signalnest.example','+1 416 555 0166',91,'Engineering blog author page','2026-09-19'],
['c_1007','Hana Suzuki','Revenue Operations Lead','KiteMetric','kitemetric.example','Revenue Intelligence','Tokyo, JP','11–50','hana.suzuki@kitemetric.example','+81 3 5550 0118',93,'Public event profile','2026-09-25'],
['c_1008','Daniel Okafor','Head of Business Development','LedgerPeak','ledgerpeak.example','Fintech','Lagos, NG','51–200','daniel.okafor@ledgerpeak.example','+234 1 555 0144',90,'Company newsroom','2026-09-21']
].map(x=>{let[id,name,title,company,domain,industry,location,employees,email,phone,confidence,source,verified]=x;return{id,name,title,company,domain,industry,location,employees,email,phone,confidence,source,verified}}),
PL=[
{id:'free',name:'Free',price:0,credits:15,features:['15 reveal credits','People & company search','Save reveal history','Community support']},
{id:'starter',name:'Starter',price:39,credits:1000,features:['1,000 reveal credits','Email + phone reveals','CSV-ready contact history','Standard support']},
{id:'growth',name:'Growth',price:99,credits:5000,popular:true,features:['5,000 reveal credits','Advanced search filters','Priority verification queue','Priority support']},
{id:'business',name:'Business',price:249,credits:15000,features:['15,000 reveal credits','Team-ready architecture','Higher rate limits','API-ready access model']}],
DEF=()=>({version:1,contacts:N.map(x=>({...x})),users:[],reveals:[],imports:[],settings:{siteName:'ContactScope',tagline:'Verified B2B contact intelligence',signupCredits:15,emailRevealCost:1,phoneRevealCost:5,plans:PL.map(x=>({...x,features:[...x.features]}))}}),
load=()=>{try{let x=JSON.parse(localStorage.getItem(K)||'null');if(x?.contacts&&x?.settings){x.imports??=[];return x}}catch{}let x=DEF();localStorage.setItem(K,JSON.stringify(x));return x},
save=x=>localStorage.setItem(K,JSON.stringify(x)),uid=x=>localStorage.getItem(K+':user'),me=x=>x.users.find(u=>u.id===uid())||null,
pub=u=>u?Object.fromEntries(Object.entries(u).filter(([k])=>k!=='password')):null,
maskE=e=>{let[a,b='']=String(e||'').split('@');return(a?.[0]||'•')+'•••••@'+b},
maskP=p=>{let s=String(p||'');return s?s.slice(0,3)+' ••• •••• '+s.slice(-2):''},
view=(c,u,d)=>({...c,email:{available:!!c.email,masked:maskE(c.email),revealed:d.reveals.some(r=>r.userId===u?.id&&r.contactId===c.id&&r.type==='email')?c.email:null,cost:d.settings.emailRevealCost},phone:{available:!!c.phone,masked:maskP(c.phone),revealed:d.reveals.some(r=>r.userId===u?.id&&r.contactId===c.id&&r.type==='phone')?c.phone:null,cost:d.settings.phoneRevealCost}}),
body=o=>{if(!o?.body)return{};if(typeof o.body==='string')try{return JSON.parse(o.body)}catch{return{}}return o.body},
resp=(x,s=200)=>Promise.resolve(new Response(JSON.stringify(x),{status:s,headers:{'Content-Type':'application/json'}})),
bad=(x,s=400)=>resp({error:x},s),native=window.fetch.bind(window);

window.fetch=async(input,o={})=>{let raw=typeof input==='string'?input:input.url,u=new URL(raw,location.href);if(!u.pathname.startsWith('/api/'))return native(input,o);
let d=load(),m=String(o.method||'GET').toUpperCase(),b=body(o),u0=me(d),p=u.pathname;
if(p==='/api/health')return resp({ok:true,storage:'browser-demo',version:2});
if(p==='/api/meta')return resp({siteName:d.settings.siteName,tagline:d.settings.tagline,signupCredits:d.settings.signupCredits,emailRevealCost:d.settings.emailRevealCost,phoneRevealCost:d.settings.phoneRevealCost,industries:[...new Set(d.contacts.map(c=>c.industry))].sort(),sizes:[...new Set(d.contacts.map(c=>c.employees))].sort()});
if(p==='/api/plans')return resp({plans:d.settings.plans,demoBilling:true});
if(p==='/api/me')return resp({user:pub(ADMIN?{id:'demo-admin',name:'Demo Administrator',email:'admin@contactscope.demo',role:'admin',planId:'business',credits:0,createdAt:new Date().toISOString()}:u0)});
if(p==='/api/auth/logout'&&m==='POST'){localStorage.removeItem(K+':user');return resp({ok:true})}
if(p==='/api/auth/signup'&&m==='POST'){let email=String(b.email||'').trim().toLowerCase(),name=String(b.name||'').trim(),password=String(b.password||'');if(name.length<2)return bad('Name is required.');if(!/^\\S+@\\S+\\.\\S+$/.test(email))return bad('Enter a valid email address.');if(password.length<10)return bad('Password must be at least 10 characters.');if(d.users.some(x=>x.email===email))return bad('An account with this email already exists.',409);let u={id:'u_'+Date.now(),name,email,password,role:email==='admin@contactscope.demo'?'admin':'user',planId:'free',credits:d.settings.signupCredits,createdAt:new Date().toISOString()};d.users.push(u);save(d);localStorage.setItem(K+':user',u.id);return resp({user:pub(u)})}
if(p==='/api/auth/login'&&m==='POST'){let email=String(b.email||'').trim().toLowerCase(),u=d.users.find(x=>x.email===email);if(!u||u.password!==String(b.password||''))return bad('Invalid email or password.',401);localStorage.setItem(K+':user',u.id);return resp({user:pub(u)})}
if(p==='/api/contacts'&&m==='GET'){let q=(u.searchParams.get('q')||'').toLowerCase(),i=u.searchParams.get('industry')||'',s=u.searchParams.get('size')||'',list=d.contacts.filter(c=>(!q||[c.name,c.title,c.company,c.domain,c.industry,c.location,c.employees].join(' ').toLowerCase().includes(q))&&(!i||c.industry===i)&&(!s||c.employees===s));return resp({total:list.length,contacts:list.map(c=>view(c,u0,d))})}
let rm=p.match(/^\/api\\/contacts\\/([^/]+)\\/reveal$/);if(rm&&m==='POST'){if(!u0)return bad('Sign in to reveal contact details.',401);let c=d.contacts.find(x=>x.id===decodeURIComponent(rm[1]));if(!c)return bad('Contact not found.',404);let t=b.type==='phone'?'phone':'email',cost=t==='phone'?d.settings.phoneRevealCost:d.settings.emailRevealCost,old=d.reveals.find(r=>r.userId===u0.id&&r.contactId===c.id&&r.type===t);if(old)return resp({value:c[t],credits:u0.credits,cost,alreadyRevealed:true});if(u0.credits<cost)return bad('Not enough credits.',402);u0.credits-=cost;d.reveals.push({id:'r_'+Date.now(),userId:u0.id,contactId:c.id,type:t,cost,at:new Date().toISOString()});save(d);return resp({value:c[t],credits:u0.credits,cost,alreadyRevealed:false})}
if(p==='/api/history'&&m==='GET'){if(!u0)return bad('Authentication required.',401);return resp({reveals:d.reveals.filter(r=>r.userId===u0.id).map(r=>{let c=d.contacts.find(x=>x.id===r.contactId);return{...r,contact:c?{name:c.name,company:c.company,value:c[r.type]}:null}})})}
if(p==='/api/billing/checkout'&&m==='POST'){if(!u0)return bad('Authentication required.',401);let pl=d.settings.plans.find(x=>x.id===b.planId);if(!pl)return bad('Plan not found.',404);u0.planId=pl.id;u0.credits+=Number(pl.credits||0);save(d);return resp({user:pub(u0),message:pl.name+' demo plan added.'})}
if(p==='/api/admin/stats')return resp({contacts:d.contacts.length,users:d.users.length,reveals:d.reveals.length,totalCredits:d.users.reduce((n,u)=>n+Number(u.credits||0),0),storage:'Browser demo',demoBilling:true,lastImport:d.imports.at(-1)||null});
if(p==='/api/admin/contacts'&&m==='GET'){let q=(u.searchParams.get('q')||'').toLowerCase();return resp({contacts:d.contacts.filter(c=>!q||Object.values(c).join(' ').toLowerCase().includes(q))})}
if(p==='/api/admin/contacts'&&m==='POST'){let c={...b,id:'c_'+Date.now()};d.contacts.push(c);save(d);return resp({contact:c})}
let cm=p.match(/^\/api\\/admin\\/contacts\\/([^/]+)$/);if(cm&&m==='PUT'){let i=d.contacts.findIndex(c=>c.id===decodeURIComponent(cm[1]));if(i<0)return bad('Contact not found.',404);d.contacts[i]={...d.contacts[i],...b};save(d);return resp({contact:d.contacts[i]})}
if(cm&&m==='DELETE'){d.contacts=d.contacts.filter(c=>c.id!==decodeURIComponent(cm[1]));save(d);return resp({ok:true})}
if(p==='/api/admin/users'&&m==='GET')return resp({users:d.users.map(u=>({...pub(u),revealCount:d.reveals.filter(r=>r.userId===u.id).length}))});
let um=p.match(/^\/api\\/admin\\/users\\/([^/]+)\\/(plan|role|credits)$/);if(um&&m==='POST'){let u=d.users.find(x=>x.id===decodeURIComponent(um[1]));if(!u)return bad('User not found.',404);if(um[2]==='plan')u.planId=b.planId;else if(um[2]==='role')u.role=b.role;else u.credits=Math.max(0,Number(u.credits||0)+Number(b.delta||0));save(d);return resp({user:pub(u)})}
if(p==='/api/admin/settings'&&m==='GET')return resp({settings:d.settings,storage:'Browser demo',demoBilling:true});
if(p==='/api/admin/settings'&&m==='PUT'){d.settings={...d.settings,...b,plans:d.settings.plans.map(x=>({...x,...((b.plans||[]).find(y=>y.id===x.id)||{})}))};save(d);return resp({settings:d.settings})}
if(p==='/api/admin/import'&&m==='POST'){let rows=String(b.csv||'').split(/\\r?\\n/).filter(Boolean),h=(rows.shift()||'').split(',').map(x=>x.trim().toLowerCase()),added=0,updated=0,skipped=0;for(let line of rows){let v=line.split(','),c={};h.forEach((k,i)=>c[k]=v[i]||'');if(!c.name||!c.company){skipped++;continue}c.id=c.id||'c_'+Date.now()+'_'+added;let i=d.contacts.findIndex(x=>x.id===c.id||(c.email&&x.email===c.email));if(i>=0){d.contacts[i]={...d.contacts[i],...c};updated++}else{c.confidence=Number(c.confidence||90);c.verified=c.verified||new Date().toISOString().slice(0,10);d.contacts.push(c);added++}}let z={at:new Date().toISOString(),mode:b.mode||'upsert',added,updated,skipped};d.imports.push(z);save(d);return resp({...z,totalErrors:0,rowErrors:[]})}
if(p==='/api/admin/contacts.csv'){let keys=['id','name','title','company','domain','industry','location','employees','email','phone','confidence','source','verified'],csv=[keys.join(','),...d.contacts.map(c=>keys.map(k=>String(c[k]??'').replace(/"/g,'""')).map(v=>'"'+v+'"').join(','))].join('\\n');return resp({csv})}
return bad('Demo API route unavailable.',503)};
document.addEventListener('click',async e=>{if(!e.target.closest?.('#downloadCsv'))return;e.preventDefault();let r=await window.fetch('/api/admin/contacts.csv'),d=await r.json(),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([d.csv],{type:'text/csv'}));a.download='contactscope-contacts.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},true);
})();